# $Id$

language: c

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    arch: amd64
  - os: linux
    dist: trusty
    compiler: clang
    arch: amd64
  - os: linux
    dist: xenial
    compiler: gcc
    arch: amd64
  - os: linux
    dist: xenial
    compiler: clang
    arch: amd64
  - os: linux
    dist: xenial
    compiler: gcc
    arch: arm64
  - os: linux
    dist: xenial
    compiler: gcc
    arch: ppc64le
  - os: linux
    dist: xenial
    compiler: gcc
    arch: s390x
  - os: linux
    dist: bionic
    compiler: gcc
    arch: amd64
  - os: linux
    dist: bionic
    compiler: clang
    arch: amd64
  - os: linux
    dist: bionic
    compiler: gcc
    arch: arm64
  - os: linux
    dist: bionic
    compiler: gcc
    arch: ppc64le
  - os: linux
    dist: bionic
    compiler: gcc
    arch: s390x
  - os: osx
    osx_image: xcode11.3
    compiler: clang

env:
 global:
  - secure: "Cq1iFAKxQ2S/LUz41BaS00+HdqTZt0hqPVlcmF4uIFRSjRocz+mKoroV2Iidbly8uuokOu5yY+ZRw8Yrjc2w8qKM+qsRHo9KNQGPx/jLe06DI2RuPcT3IxnGrElLDUUs2qJ6drjGCrOEFP2eowMdytqLDJfKW5OGLOFsmoSIwD0="

compiler:
 - gcc
 - clang

addons:
  coverity_scan:
    project:
      name: "ircd-hybrid/ircd-hybrid"
      description: "A lightweight, high-performance internet relay chat daemon."
    notification_email: bugs@ircd-hybrid.org
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan

script:
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./configure --with-tls=none --enable-assert; else ./configure --enable-assert; fi
 - make
 - sudo make install

notifications:
 email:
  - bugs@ircd-hybrid.org
 irc:
  channels:
  - "irc.ircd-hybrid.org#ircd-coders"
  skip_join: true
